### ISSUE TITLE
sqlite: consider dropping upsert for replace

### ISSUE THREAD

**Issue by dberenbaum** [iterative/sqltrie#12]
Background in [slack](https://iterativeai.slack.com/archives/C03JS2V4MQU/p1678475968146249?thread_ts=1678464362.727829&cid=C03JS2V4MQU).

Do we need upsert, or would `replace` be good enough?

https://github.com/iterative/sqltrie/blob/99ee92982aefbe99d42eff40161aa2a828efa3eb/src/sqltrie/sqlite/sqlite.py#L164-L167

It would be nice to work with older sqlite versions.

cc @efiop

**Comment by efiop** [comment]
Related https://github.com/iterative/sqltrie/pull/10

We had some problems with `views` and `INSERT OR REPLACE` before, but now it `view` using original connection it might actually be enough.

**Comment by efiop** [comment]
Ah, still can't use it, unfortunately. REPLACE deletes old record and so always updates id(rowid), which is breaking the table. We'll have to go with either two queries or a trigger.
