### ISSUE TITLE
sqlite: don't use TRUE/FALSE

### ISSUE THREAD

**Issue by efiop** [iterative/sqltrie#8]
These are not supported in older sqlite versions https://stackoverflow.com/questions/75670745/error-unexpected-error-no-such-column-false-on-dvc-pull

**Comment by skshetry** [comment]
I think it's better to be within `sqlite>=3.7.15`, same as Python 3.10.

**Comment by efiop** [comment]
Fixed by https://github.com/iterative/sqltrie/pull/9

**Comment by efiop** [comment]
@skshetry Lets see how much we can get away with.
